import { Metadata } from 'next'
import Head from 'next/head'
import "../styles/globals.css";
import { Providers } from './providers';

export async function metadata(): Promise<Metadata> {
  return {
    title: 'Root - Nextron (with-tailwindcss)',
    description: 'Generated by Next.js',
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
