import { Metadata } from 'next'
import Head from 'next/head'

export async function metadata(): Promise<Metadata> {
  return {
    title: 'Home - Nextron (with-tailwindcss)',
    description: 'Generated by Next.js',
  }
}

export default function HomeLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div>
      <body>{children}</body>
    </div>
  )
}
